//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lotteries
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lotteries()
        {
            this.Tickets = new HashSet<Tickets>();
            this.Draws = new HashSet<Draws>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public decimal ticket_price { get; set; }
        public System.DateTime start_time { get; set; }
        public string end_time { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tickets> Tickets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Draws> Draws { get; set; }
    }
}
