//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module
{
    using System;
    using System.Collections.Generic;
    
    public partial class Winners
    {
        public int Id { get; set; }
        public int draw_id_fk { get; set; }
        public int user_id_fk { get; set; }
        public decimal prize_amount { get; set; }
    
        public virtual Draws Draw { get; set; }
        public virtual Users User { get; set; }
    }
}
